### ISSUE TITLE
Renomear funções

### ISSUE THREAD

**Issue by timarcosdias** [douradoanderson/Geometria-Plana#1]
Recomendo a utilização de nomes em formato camelCase sem acentos nas funções.

Em vez de: `TRIÂNGULO()`, utilizar `triangulo()`.

**Comment by douradoanderson** [comment]
Eu tinha esquecido de colocar em formato camelCase na hora que estava fazendo, coloquei no formato adequado o arquivo biblioteca.js. Só não alterei os da pasta zipada.
